codecov:
  token: "dad7732d-7fb3-472e-82c0-a3234ce83b8d"
ignore:
  - "**/AppDelegate.swift"
  - "**/*View.swift"
  - "**/*ViewController.swift"
  - "**/*Cell.swift"
  - "**/*ModuleBuilder.swift"
  - "**/*Button.swift"
  - "**/*Style.swift"
  - "**/*Localization.swift"
  - "**/Extensions/View/*.swift"
  - "**/*Router.swift"
  - "**/RealmExpensesRepositoryFactory.swift"
  - "**/Color+hex.swift"