coverage_service: cobertura_xml
xcodeproj: Kakebo.xcodeproj
workspace: Kakebo.xcworkspace
scheme: Kakebo
source_directory: Kakebo
output_directory: slather

ignore:
  - "**/AppDelegate.swift"
  - "**/*View.swift"
  - "**/*ViewController.swift"
  - "**/*Cell.swift"
  - "**/*ModuleBuilder.swift"
  - "**/*Button.swift"
  - "**/*Style.swift"
  - "**/*Localization.swift"
  - "**/Extensions/View/*.swift"
  - "**/*Router.swift"
  - "**/RealmExpensesRepositoryFactory.swift"
  - "**/Color+hex.swift"