language: swift
osx_image: xcode10.2

env:
  - CODECOV_TOKEN="dad7732d-7fb3-472e-82c0-a3234ce83b8d"
 
cache:
  directories:
    - Carthage

xcode_project: Kakebo.xcodeproj
xcode_scheme: Kakebo
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - brew install xcodegen || true
  - brew outdated xcodegen || brew upgrade xcodegen
  - rvm use $RVM_RUBY_VERSION

install: bundle install --without=documentation --path ../travis_bundle_dir

before_script:
  - travis_wait 60 carthage bootstrap --platform iOS --cache-builds
  - xcodegen

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f slather/c  obertura.xml -X coveragepy -X gcov -X xcode
  