language: swift
osx_image: xcode11.3

env:
  - CODECOV_TOKEN="dad7732d-7fb3-472e-82c0-a3234ce83b8d"

xcode_workspace: Kakebo.xcworkspace
xcode_scheme: Kakebo
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

before_install:
  - rvm use $RVM_RUBY_VERSION

install: 
  - bundle install --without=documentation --path ../travis_bundle_dir

after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash) -f slather/cobertura.xml -X coveragepy -X gcov -X xcode
  