language: swift
osx_image: xcode10.2
xcode_project: Kakebo.xcodeproj
xcode_scheme: KakeboTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds