language: swift
osx_image: xcode11.4

xcode_workspace: Kakebo.xcworkspace
xcode_scheme: Kakebo
xcode_destination: platform=iOS Simulator,OS=13.4,name=iPhone 11

after_success:
  - bash <(curl -s https://codecov.io/bash)
  