name: Kakebo

options:
  bundleIdPrefix: com.sbs
  xcodeVersion: 10.2
  usesTabs: false
  indentWidth: 2
  deploymentTarget:
    iOS: 11.0

settings:
  base: 
    SWIFT_VERSION: 5
    
targets:
  Kakebo:
    type: application
    platform: iOS
    sources:
      - kakebo
    dependencies:
      - carthage: Realm
      - carthage: RealmSwift
    settings:
      base:
        TARGETED_DEVICE_FAMILY: '1'
      configs:
        Release:
          SWIFT_COMPILATION_MODE: 'wholemodule'
    preBuildScripts:
      - name: Swift lint
        script: |
                if which swiftlint >/dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi

  KakeboTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - kakeboTests
    dependencies:
      - target: Kakebo
      - carthage: Quick
      - carthage: Nimble

schemes:
  Kakebo:
    build:
      targets:
        Kakebo: all
    test:
      gatherCoverageData: true
      targets:
        - KakeboTests
